# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e98566f5609f762dc88db751422550bd31b69fbb3aeb4d7ace7a64306148a79b598a0229877f5390ed20ed7869729e2d33baad550af5b094dff81ede186b78c

test:
  secret_key_base: 4ac1ea3385a617028d7818eef20150b9f10517431226dd2794f111253eaabfea3eca7da36b9ab128ffccb65e44827de28f85a97993978ce55b680d0b5f37bcba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
